spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myLibrary
    username: spring
    password: spring123

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
